import pytest
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.append(os.path.join(ROOT, "src"))
from simulator import hard_policy, soft_policy, split_policy
from blackjack import Actions


def test_hard_policy():
    assert (
        hard_policy[4]
        == hard_policy[5]
        == hard_policy[6]
        == hard_policy[7]
        == hard_policy[8]
    )
    assert all([i == Actions.HIT for i in hard_policy[4].values()])
    assert hard_policy[9][2] == Actions.HIT
    assert hard_policy[9][3] == Actions.DOUBLE_HIT
    assert hard_policy[9][4] == Actions.DOUBLE_HIT
    assert hard_policy[9][5] == Actions.DOUBLE_HIT
    assert hard_policy[9][6] == Actions.DOUBLE_HIT
    assert hard_policy[9][7] == Actions.HIT
    assert hard_policy[9][8] == Actions.HIT
    assert hard_policy[9][9] == Actions.HIT
    assert hard_policy[9][10] == Actions.HIT
    assert hard_policy[9][11] == Actions.HIT
    assert hard_policy[10][2] == Actions.DOUBLE_HIT
    assert hard_policy[10][3] == Actions.DOUBLE_HIT
    assert hard_policy[10][4] == Actions.DOUBLE_HIT
    assert hard_policy[10][5] == Actions.DOUBLE_HIT
    assert hard_policy[10][6] == Actions.DOUBLE_HIT
    assert hard_policy[10][7] == Actions.DOUBLE_HIT
    assert hard_policy[10][8] == Actions.DOUBLE_HIT
    assert hard_policy[10][9] == Actions.DOUBLE_HIT
    assert hard_policy[10][10] == Actions.HIT
    assert hard_policy[10][11] == Actions.HIT
    assert hard_policy[11][2] == Actions.DOUBLE_HIT
    assert hard_policy[11][3] == Actions.DOUBLE_HIT
    assert hard_policy[11][4] == Actions.DOUBLE_HIT
    assert hard_policy[11][5] == Actions.DOUBLE_HIT
    assert hard_policy[11][6] == Actions.DOUBLE_HIT
    assert hard_policy[11][7] == Actions.DOUBLE_HIT
    assert hard_policy[11][8] == Actions.DOUBLE_HIT
    assert hard_policy[11][9] == Actions.DOUBLE_HIT
    assert hard_policy[11][10] == Actions.DOUBLE_HIT
    assert hard_policy[11][11] == Actions.DOUBLE_HIT
    assert hard_policy[12][2] == Actions.HIT
    assert hard_policy[12][3] == Actions.HIT
    assert hard_policy[12][4] == Actions.STAND
    assert hard_policy[12][5] == Actions.STAND
    assert hard_policy[12][6] == Actions.STAND
    assert hard_policy[12][7] == Actions.HIT
    assert hard_policy[12][8] == Actions.HIT
    assert hard_policy[12][9] == Actions.HIT
    assert hard_policy[12][10] == Actions.HIT
    assert hard_policy[12][11] == Actions.HIT
    assert hard_policy[13][2] == Actions.STAND
    assert hard_policy[13][3] == Actions.STAND
    assert hard_policy[13][4] == Actions.STAND
    assert hard_policy[13][5] == Actions.STAND
    assert hard_policy[13][6] == Actions.STAND
    assert hard_policy[13][7] == Actions.HIT
    assert hard_policy[13][8] == Actions.HIT
    assert hard_policy[13][9] == Actions.HIT
    assert hard_policy[13][10] == Actions.HIT
    assert hard_policy[13][11] == Actions.HIT
    assert hard_policy[14][2] == Actions.STAND
    assert hard_policy[14][3] == Actions.STAND
    assert hard_policy[14][4] == Actions.STAND
    assert hard_policy[14][5] == Actions.STAND
    assert hard_policy[14][6] == Actions.STAND
    assert hard_policy[14][7] == Actions.HIT
    assert hard_policy[14][8] == Actions.HIT
    assert hard_policy[14][9] == Actions.HIT
    assert hard_policy[14][10] == Actions.HIT
    assert hard_policy[14][11] == Actions.HIT
    assert hard_policy[15][2] == Actions.STAND
    assert hard_policy[15][3] == Actions.STAND
    assert hard_policy[15][4] == Actions.STAND
    assert hard_policy[15][5] == Actions.STAND
    assert hard_policy[15][6] == Actions.STAND
    assert hard_policy[15][7] == Actions.HIT
    assert hard_policy[15][8] == Actions.HIT
    assert hard_policy[15][9] == Actions.HIT
    assert hard_policy[15][10] == Actions.SURRENDER_HIT
    assert hard_policy[15][11] == Actions.SURRENDER_HIT
    assert hard_policy[16][2] == Actions.STAND
    assert hard_policy[16][3] == Actions.STAND
    assert hard_policy[16][4] == Actions.STAND
    assert hard_policy[16][5] == Actions.STAND
    assert hard_policy[16][6] == Actions.STAND
    assert hard_policy[16][7] == Actions.HIT
    assert hard_policy[16][8] == Actions.HIT
    assert hard_policy[16][9] == Actions.SURRENDER_HIT
    assert hard_policy[16][10] == Actions.SURRENDER_HIT
    assert hard_policy[16][11] == Actions.SURRENDER_HIT
    assert hard_policy[17][2] == Actions.STAND
    assert hard_policy[17][3] == Actions.STAND
    assert hard_policy[17][4] == Actions.STAND
    assert hard_policy[17][5] == Actions.STAND
    assert hard_policy[17][6] == Actions.STAND
    assert hard_policy[17][7] == Actions.STAND
    assert hard_policy[17][8] == Actions.STAND
    assert hard_policy[17][9] == Actions.STAND
    assert hard_policy[17][10] == Actions.STAND
    assert hard_policy[17][11] == Actions.SURRENDER_STAND
    assert hard_policy[18][2] == Actions.STAND
    assert hard_policy[18][3] == Actions.STAND
    assert hard_policy[18][4] == Actions.STAND
    assert hard_policy[18][5] == Actions.STAND
    assert hard_policy[18][6] == Actions.STAND
    assert hard_policy[18][7] == Actions.STAND
    assert hard_policy[18][8] == Actions.STAND
    assert hard_policy[18][9] == Actions.STAND
    assert hard_policy[18][10] == Actions.STAND
    assert hard_policy[18][11] == Actions.STAND


def test_soft_policy():
    assert soft_policy[13][2] == Actions.HIT
    assert soft_policy[13][3] == Actions.HIT
    assert soft_policy[13][4] == Actions.HIT
    assert soft_policy[13][5] == Actions.DOUBLE_HIT
    assert soft_policy[13][6] == Actions.DOUBLE_HIT
    assert soft_policy[13][7] == Actions.HIT
    assert soft_policy[13][8] == Actions.HIT
    assert soft_policy[13][9] == Actions.HIT
    assert soft_policy[13][10] == Actions.HIT
    assert soft_policy[13][11] == Actions.HIT
    assert soft_policy[14][2] == Actions.HIT
    assert soft_policy[14][3] == Actions.HIT
    assert soft_policy[14][4] == Actions.HIT
    assert soft_policy[14][5] == Actions.DOUBLE_HIT
    assert soft_policy[14][6] == Actions.DOUBLE_HIT
    assert soft_policy[14][7] == Actions.HIT
    assert soft_policy[14][8] == Actions.HIT
    assert soft_policy[14][9] == Actions.HIT
    assert soft_policy[14][10] == Actions.HIT
    assert soft_policy[14][11] == Actions.HIT
    assert soft_policy[15][2] == Actions.HIT
    assert soft_policy[15][3] == Actions.HIT
    assert soft_policy[15][4] == Actions.DOUBLE_HIT
    assert soft_policy[15][5] == Actions.DOUBLE_HIT
    assert soft_policy[15][6] == Actions.DOUBLE_HIT
    assert soft_policy[15][7] == Actions.HIT
    assert soft_policy[15][8] == Actions.HIT
    assert soft_policy[15][9] == Actions.HIT
    assert soft_policy[15][10] == Actions.HIT
    assert soft_policy[15][11] == Actions.HIT
    assert soft_policy[14][11] == Actions.HIT
    assert soft_policy[16][2] == Actions.HIT
    assert soft_policy[16][3] == Actions.HIT
    assert soft_policy[16][4] == Actions.DOUBLE_HIT
    assert soft_policy[16][5] == Actions.DOUBLE_HIT
    assert soft_policy[16][6] == Actions.DOUBLE_HIT
    assert soft_policy[16][7] == Actions.HIT
    assert soft_policy[16][8] == Actions.HIT
    assert soft_policy[16][9] == Actions.HIT
    assert soft_policy[16][10] == Actions.HIT
    assert soft_policy[16][11] == Actions.HIT
    assert soft_policy[17][2] == Actions.HIT
    assert soft_policy[17][3] == Actions.DOUBLE_HIT
    assert soft_policy[17][4] == Actions.DOUBLE_HIT
    assert soft_policy[17][5] == Actions.DOUBLE_HIT
    assert soft_policy[17][6] == Actions.DOUBLE_HIT
    assert soft_policy[17][7] == Actions.HIT
    assert soft_policy[17][8] == Actions.HIT
    assert soft_policy[17][9] == Actions.HIT
    assert soft_policy[17][10] == Actions.HIT
    assert soft_policy[17][11] == Actions.HIT
    assert soft_policy[18][2] == Actions.DOUBLE_STAND
    assert soft_policy[18][3] == Actions.DOUBLE_STAND
    assert soft_policy[18][4] == Actions.DOUBLE_STAND
    assert soft_policy[18][5] == Actions.DOUBLE_STAND
    assert soft_policy[18][6] == Actions.DOUBLE_STAND
    assert soft_policy[18][7] == Actions.STAND
    assert soft_policy[18][8] == Actions.STAND
    assert soft_policy[18][9] == Actions.HIT
    assert soft_policy[18][10] == Actions.HIT
    assert soft_policy[18][11] == Actions.HIT
    assert soft_policy[19][2] == Actions.STAND
    assert soft_policy[19][3] == Actions.STAND
    assert soft_policy[19][4] == Actions.STAND
    assert soft_policy[19][5] == Actions.STAND
    assert soft_policy[19][6] == Actions.DOUBLE_STAND
    assert soft_policy[19][7] == Actions.STAND
    assert soft_policy[19][8] == Actions.STAND
    assert soft_policy[19][9] == Actions.STAND
    assert soft_policy[19][10] == Actions.STAND
    assert soft_policy[19][11] == Actions.STAND
    assert soft_policy[20][2] == Actions.STAND
    assert soft_policy[20][3] == Actions.STAND
    assert soft_policy[20][4] == Actions.STAND
    assert soft_policy[20][5] == Actions.STAND
    assert soft_policy[20][6] == Actions.STAND
    assert soft_policy[20][7] == Actions.STAND
    assert soft_policy[20][8] == Actions.STAND
    assert soft_policy[20][9] == Actions.STAND
    assert soft_policy[20][10] == Actions.STAND
    assert soft_policy[20][11] == Actions.STAND


def test_split_policy():
    assert split_policy[2][2] == Actions.SPLIT_IF_DOUBLE
    assert split_policy[2][3] == Actions.SPLIT_IF_DOUBLE
    assert split_policy[2][4] == Actions.SPLIT
    assert split_policy[2][5] == Actions.SPLIT
    assert split_policy[2][6] == Actions.SPLIT
    assert split_policy[2][7] == Actions.SPLIT
    assert split_policy[2][8] == Actions.HIT
    assert split_policy[2][9] == Actions.HIT
    assert split_policy[2][10] == Actions.HIT
    assert split_policy[2][11] == Actions.HIT
    assert split_policy[2] == split_policy[3]
    assert split_policy[4][2] == Actions.HIT
    assert split_policy[4][3] == Actions.HIT
    assert split_policy[4][4] == Actions.HIT
    assert split_policy[4][5] == Actions.SPLIT_IF_DOUBLE
    assert split_policy[4][6] == Actions.SPLIT_IF_DOUBLE
    assert split_policy[4][7] == Actions.HIT
    assert split_policy[4][8] == Actions.HIT
    assert split_policy[4][9] == Actions.HIT
    assert split_policy[4][10] == Actions.HIT
    assert split_policy[4][11] == Actions.HIT
    assert split_policy[5] == hard_policy[10]
    assert split_policy[6][2] == Actions.SPLIT_IF_DOUBLE
    assert split_policy[6][3] == Actions.SPLIT
    assert split_policy[6][4] == Actions.SPLIT
    assert split_policy[6][5] == Actions.SPLIT
    assert split_policy[6][6] == Actions.SPLIT
    assert split_policy[6][7] == Actions.HIT
    assert split_policy[6][8] == Actions.HIT
    assert split_policy[6][9] == Actions.HIT
    assert split_policy[6][10] == Actions.HIT
    assert split_policy[6][11] == Actions.HIT
    assert split_policy[7][2] == Actions.SPLIT
    assert split_policy[7][3] == Actions.SPLIT
    assert split_policy[7][4] == Actions.SPLIT
    assert split_policy[7][5] == Actions.SPLIT
    assert split_policy[7][6] == Actions.SPLIT
    assert split_policy[7][7] == Actions.SPLIT
    assert split_policy[7][8] == Actions.HIT
    assert split_policy[7][9] == Actions.HIT
    assert split_policy[7][10] == Actions.HIT
    assert split_policy[7][11] == Actions.HIT
    assert split_policy[8][2] == Actions.SPLIT
    assert split_policy[8][3] == Actions.SPLIT
    assert split_policy[8][4] == Actions.SPLIT
    assert split_policy[8][5] == Actions.SPLIT
    assert split_policy[8][6] == Actions.SPLIT
    assert split_policy[8][7] == Actions.SPLIT
    assert split_policy[8][8] == Actions.SPLIT
    assert split_policy[8][9] == Actions.SPLIT
    assert split_policy[8][10] == Actions.SPLIT
    assert split_policy[8][11] == Actions.SURRENDER_SPLIT
    assert split_policy[9][2] == Actions.SPLIT
    assert split_policy[9][3] == Actions.SPLIT
    assert split_policy[9][4] == Actions.SPLIT
    assert split_policy[9][5] == Actions.SPLIT
    assert split_policy[9][6] == Actions.SPLIT
    assert split_policy[9][7] == Actions.STAND
    assert split_policy[9][8] == Actions.SPLIT
    assert split_policy[9][9] == Actions.SPLIT
    assert split_policy[9][10] == Actions.STAND
    assert split_policy[9][11] == Actions.STAND
    assert split_policy[10] == hard_policy[20]
    assert split_policy[11][2] == Actions.SPLIT
    assert split_policy[11][3] == Actions.SPLIT
    assert split_policy[11][4] == Actions.SPLIT
    assert split_policy[11][5] == Actions.SPLIT
    assert split_policy[11][6] == Actions.SPLIT
    assert split_policy[11][7] == Actions.SPLIT
    assert split_policy[11][8] == Actions.SPLIT
    assert split_policy[11][9] == Actions.SPLIT
    assert split_policy[11][10] == Actions.SPLIT
    assert split_policy[11][11] == Actions.SPLIT
